apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nextjs
  namespace: devops-challenge
  labels:
    app.kubernetes.io/component: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextjs
