apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-challenge
  labels:
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
